version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: daily
    target-branch: development
    default_labels: "dependency"
    commit-message:
      prefix: "[DEPENDABOT]"