micronaut:
    application:
        name: sampletracking
    security:
        enabled: true
        endpoints:
            login:
                enabled: true
datasources:
        default:
            url: jdbc:hsqldb:mem:mymemdb;shutdown=true/test?maxPoolSize=150&pool
            username: testuser
            driver-class-name: org.hsqldb.jdbc.JDBCDriver
            password: ""
userroles:
    config: "src/test/resources/userroles.yml"