micronaut:
    application:
        name: sampletracking
    server:
        port: ${tr-server-port:8080}
    router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: /swagger/**
            swagger-ui:
                paths: classpath:META-INF/swagger/views/swagger-ui
                mapping: /swagger-ui/**
            rapidoc:
                paths: classpath:META-INF/swagger/views/rapidoc
                mapping: /rapidoc/**
    security:
        enabled: true
        endpoints:
            login:
                enabled: true
datasources:
    default:
        url: jdbc:mariadb://${tr-db-host}/${tr-db-name}?maxPoolSize=20&pool=true
        username: ${tr-db-user}
        password: ${tr-db-pwd}
        driverClassName: org.mariadb.jdbc.Driver
userroles:
    config: ${domain-userroles:/etc/micronaut.d/userroles.yml}
database:
    name: ${tr-db-name}
endpoints:
    health:
        enabled: true
        sensitive: false
        details-visible: ANONYMOUS
    routes:
        enabled: true
        sensitive: false
